security:
  encoders:
    ScayTrase\Symfony\Sample\Blog\Entity\User: bcrypt

  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER, ROLE_AUTHOR, ROLE_ALLOWED_TO_SWITCH]
    ROLE_AUTHOR: [ROLE_USER]
    ROLE_USER: []

  providers:
    db_provider:
      entity:
        class: ScayTrase\Symfony\Sample\Blog\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    default:
      pattern: ^/
      anonymous: ~
      form_login:
        check_path: login_check
        login_path: login
        use_referer: true
        default_target_path: index
      logout:
        path:   logout
        target: index

  access_control:
    - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
